#!/usr/bin/env python3
# TBH-BugBounty v2.0 Pro - JSON + HTML Report for HackerOne
import socket, requests, argparse, json, ssl
from datetime import datetime
from urllib.parse import urlparse

BANNER = """\033[91m╔════════════════════════════════════╗
\033[91m║ \033[97mTBH-BugBounty v2.0 Pro \033[91m- HTML/JSON \033[91m║
\033[91m║ \033[90mTulungagung Black Hat | uchil404 \033[91m║
\033[91m╚════════════════════════════════════╝\033[0m"""

def recon(url):
    domain=urlparse(url if url.startswith("http") else "https://"+url).hostname or urlparse(url if url.startswith("http") else "https://"+url).netloc
    ip=socket.gethostbyname(domain)
    print(f"[*] Target: {domain} ({ip})")
    report={"target":domain,"ip":ip,"url":url,"time":str(datetime.now())}
    try:
        r=requests.get(url,timeout=5,headers={'User-Agent':'TBH-BugBounty/2.0'})
        missing=[h for h in ['Content-Security-Policy','Strict-Transport-Security','X-Frame-Options'] if h not in r.headers]
        report["headers"]={"status":r.status_code,"server":r.headers.get('Server','Unknown'),"missing":missing}
        print(f"[+] Headers: {r.status_code} | Missing: {missing or 'none'}")
    except Exception as e: report["headers"]={"error":str(e)}
    try:
        ctx=ssl.create_default_context()
        with ctx.wrap_socket(socket.socket(),server_hostname=domain) as s:
            s.settimeout(3); s.connect((domain,443)); cert=s.getpeercert()
            expire=cert.get('notAfter'); days=(datetime.strptime(expire,"%b %d %H:%M:%S %Y %Z")-datetime.utcnow()).days
            report["ssl"]={"expire":expire,"days":days}
            print(f"[+] SSL: {days} days")
    except: report["ssl"]={"note":"no https"}
    open_ports=[]
    for p in [80,443,8080,8443]:
        s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.settimeout(1)
        if s.connect_ex((ip,p))==0: open_ports.append(p); print(f"[OPEN] {p}")
        s.close()
    report["ports"]=open_ports
    found=[]
    for sub in ['www','api','admin','test']:
        try: socket.gethostbyname(f"{sub}.{domain}"); found.append(f"{sub}.{domain}")
        except: pass
    report["subdomains"]=found
    return report

def main():
    print(BANNER)
    print("\033[91m[!] Hanya untuk scope yang diizinkan!\033[0m\n")
    parser=argparse.ArgumentParser(description="v2.0 Pro")
    parser.add_argument("-u","--url",required=True)
    parser.add_argument("--json",help="Save JSON")
    parser.add_argument("--html",help="Save HTML report")
    args=parser.parse_args()
    report=recon(args.url)
    print("\n--- Saran Laporan ---")
    if report["headers"].get("missing"): print(f"- Missing {report['headers']['missing']} (Low)")
    if report["ssl"].get("days",999)<30: print(f"- SSL {report['ssl']['days']} days (Medium)")
    if args.json:
        open(args.json,'w').write(json.dumps(report,indent=2)); print(f"[✓] JSON: {args.json}")
    if args.html:
        html=f"""<html><head><title>TBH-BugBounty Pro Report {report['target']}</title></head><body style="font-family:monospace;background:#0d1117;color:#c9d1d9;padding:20px">
<h1 style="color:#ff0000">TBH-BugBounty Pro Report - {report['target']} ({report['ip']})</h1>
<p>Time: {report['time']}</p>
<h2>Headers</h2><pre>{json.dumps(report['headers'],indent=2)}</pre>
<h2>SSL</h2><pre>{json.dumps(report['ssl'],indent=2)}</pre>
<h2>Ports</h2><pre>{report['ports']}</pre>
<h2>Subdomains</h2><pre>{report['subdomains']}</pre>
<p>Generated by TBH-BugBounty v2.0 Pro - Tulungagung Black Hat</p>
</body></html>"""
        open(args.html,'w').write(html); print(f"[✓] HTML: {args.html}")

if __name__=="__main__": main()
